"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";

import type { Catalogue, RunPlan, WorkflowShape } from "../lib/api";
import { createRun, deleteRun, getCatalogue, planRun, startRun, uploadInput } from "../lib/api";
import { duration, fileSize, initial, money } from "../lib/format";

/**
 * New run — drop the data, say what you want to know, read the plan, start.
 *
 * No wizard and no chat. One surface, and between the file and the Start button
 * exactly one thing: **a plan you can read and edit**. That is the pattern the
 * research puts at the top of what a new entrant can own — approval *before*
 * execution rather than review after it — and the plan is an artifact of the
 * run rather than a screen: it is stored, it is what the audit trail opens with,
 * and the cost it quotes is what past runs of this workflow actually cost.
 *
 * Nothing here is generated by a model. A proposal a person is about to approve
 * should not itself be able to hallucinate.
 */
export default function NewRun() {
  const router = useRouter();
  const catalogue = useCatalogue();
  const workflows = catalogue?.workflows ?? [];
  const replay = catalogue?.replay ?? null;

  const [chosen, setChosen] = useState<string | null>(null);
  const workflow = workflows.find((w) => w.name === (chosen ?? replay ?? workflows[0]?.name));

  const [file, setFile] = useState<File | null>(null);
  const [question, setQuestion] = useState("");
  const [values, setValues] = useState<Record<string, string>>({});
  const [plan, setPlan] = useState<RunPlan | null>(null);
  const [runId, setRunId] = useState<string | null>(null);
  const [busy, setBusy] = useState<"" | "planning" | "starting">("");
  const [error, setError] = useState<string | null>(null);

  const dataInput = workflow ? fileInputOf(workflow) : null;

  /**
   * Create the run, upload the file, and ask what it will do.
   *
   * The run has to exist first: it is where the file lands and what the plan is
   * stored on. It exists as `pending` and nothing has been spent — and if this
   * fails halfway, the empty run is deleted rather than left at the top of the
   * ledger for ever.
   */
  async function propose() {
    if (!workflow || !file || !dataInput) return;
    setBusy("planning");
    setError(null);
    let created: string | null = null;
    try {
      const run = await createRun(workflow.name, filled({ ...values, question }));
      created = run.run_id;
      await uploadInput(created, dataInput, file);
      const proposed = await planRun(created);
      setRunId(created);
      setPlan(proposed);
      setValues((v) => ({ ...guessed(proposed), ...v }));
    } catch (e) {
      if (created) void deleteRun(created).catch(() => undefined);
      setRunId(null);
      setError((e as Error).message);
    } finally {
      setBusy("");
    }
  }

  async function start() {
    if (!runId) return;
    setBusy("starting");
    setError(null);
    try {
      await startRun(runId);
      router.push(`/runs/${encodeURIComponent(runId)}`);
    } catch (e) {
      setError((e as Error).message);
      setBusy("");
    }
  }

  if (!catalogue) {
    return (
      <main className="page">
        <p className="dim">Reading the cartridge…</p>
      </main>
    );
  }

  return (
    <main className="page">
      <div className="page-head">
        <div>
          <h1 className="page-title">New run</h1>
          <p className="page-sub">
            Drop the data and say what you want to know. You will see who works on it, in what
            order, where it stops to ask you something, and what it is likely to cost — before
            anything runs.
          </p>
        </div>
        <Link href="/" className="btn btn-quiet">
          Back to runs
        </Link>
      </div>

      {error && <div className="notice">{error}</div>}

      {workflows.length > 1 && !plan && (
        <div className="choices">
          {workflows.map((w) => (
            <button
              key={w.name}
              type="button"
              className={`choice${w.name === workflow?.name ? " is-on" : ""}`}
              onClick={() => setChosen(w.name)}
            >
              <b>{w.name}</b>
              <span>{w.description}</span>
              <span className="choice-team">
                {w.personas.map((p) => (
                  <span key={p} className="avatar is-tiny">
                    {initial(p)}
                  </span>
                ))}
                {w.steps.length} steps · {w.steps.filter((s) => s.gate).length} stop
                {w.steps.filter((s) => s.gate).length === 1 ? "" : "s"} for you
              </span>
            </button>
          ))}
        </div>
      )}

      <div className="new-grid">
        <section>
          <Drop file={file} onFile={setFile} disabled={Boolean(plan)} />
          <label className="field" htmlFor="question">
            What do you want to know?
          </label>
          <textarea
            id="question"
            rows={3}
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder={workflow?.inputs?.question?.default ?? "Ask the team a question…"}
            disabled={Boolean(plan)}
          />
          {!plan && (
            <p className="new-actions">
              <button
                type="button"
                className="btn btn-primary"
                onClick={() => void propose()}
                disabled={!file || busy !== ""}
              >
                {busy === "planning" ? "Reading the file…" : "Propose a plan"}
              </button>
              <span className="dim">Nothing runs yet. The file does not leave this server.</span>
            </p>
          )}
        </section>

        {plan && workflow && (
          <Plan
            plan={plan}
            values={values}
            onChange={(key, value) => setValues((v) => ({ ...v, [key]: value }))}
            onStart={() => void start()}
            starting={busy === "starting"}
          />
        )}
      </div>
    </main>
  );
}

/** The drop zone, and what the file turned out to be. */
function Drop({
  file,
  onFile,
  disabled,
}: {
  file: File | null;
  onFile: (file: File) => void;
  disabled: boolean;
}) {
  const input = useRef<HTMLInputElement>(null);
  const [over, setOver] = useState(false);

  return (
    <>
      <div
        className={`drop${over ? " is-over" : ""}${file ? " is-full" : ""}`}
        onClick={() => !disabled && input.current?.click()}
        onDragOver={(e) => {
          e.preventDefault();
          setOver(true);
        }}
        onDragLeave={() => setOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setOver(false);
          const dropped = e.dataTransfer.files[0];
          if (dropped && !disabled) onFile(dropped);
        }}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === "Enter" && input.current?.click()}
      >
        <span className="drop-big">
          {file ? file.name : "Drop a CSV, TSV or parquet"}
        </span>
        <span className="drop-sub">
          {file
            ? fileSize(file.size)
            : "or click to choose one · the data stays on your server"}
        </span>
      </div>
      <input
        ref={input}
        type="file"
        hidden
        accept=".csv,.tsv,.parquet,.pq"
        onChange={(e) => e.target.files?.[0] && onFile(e.target.files[0])}
      />
    </>
  );
}

/** The proposal: what it read, who works, where it stops, what it costs. */
function Plan({
  plan,
  values,
  onChange,
  onStart,
  starting,
}: {
  plan: RunPlan;
  values: Record<string, string>;
  onChange: (key: string, value: string) => void;
  onStart: () => void;
  starting: boolean;
}) {
  return (
    <section className="plan">
      <p className="plan-eyebrow">The plan</p>
      <h2 className="plan-name">{plan.workflow}</h2>
      <p className="plan-desc">{plan.description}</p>

      {plan.profile && (
        <p className="plan-file">
          <span className="mono">{plan.profile.path}</span> · {plan.profile.rows.toLocaleString()}{" "}
          rows × {plan.profile.columns.length} columns · {fileSize(plan.profile.bytes)}
          <br />
          <span className="dim">
            {plan.profile.columns.map((c) => c.name).join(", ")}
          </span>
        </p>
      )}

      {Object.keys(plan.guesses).length > 0 && (
        <div className="plan-inputs">
          {Object.entries(plan.guesses).map(([key, guess]) => (
            <label key={key}>
              <b>{key}</b>
              <input
                value={values[key] ?? guess.value}
                onChange={(e) => onChange(key, e.target.value)}
                aria-label={key}
              />
              <span className="dim">guessed: {guess.why}</span>
            </label>
          ))}
        </div>
      )}

      <p className="plan-eyebrow">Who does what</p>
      <ol className="plan-steps">
        {plan.steps.map((step) => (
          <li key={step.id} className={step.gate ? "is-gate" : undefined}>
            <b>{step.id}</b>
            <span>
              {step.persona}
              {step.section ? ` · ${step.section.toLowerCase()}` : ""}
            </span>
            {step.gate && <span className="plan-gate">then it asks you</span>}
          </li>
        ))}
      </ol>

      <dl className="plan-estimate">
        <Figure
          label="likely cost"
          value={plan.estimate.cost_usd == null ? "unknown" : money(plan.estimate.cost_usd)}
        />
        <Figure
          label="likely time"
          value={plan.estimate.seconds == null ? "unknown" : duration(plan.estimate.seconds)}
        />
        <Figure label="your decisions" value={String(plan.gates.length)} />
        <Figure
          label="based on"
          value={plan.estimate.runs === 0 ? "no past run" : `${plan.estimate.runs} runs`}
        />
      </dl>

      <p className="new-actions">
        <button type="button" className="btn btn-primary" onClick={onStart} disabled={starting}>
          {starting ? "Starting…" : "Start the run"}
        </button>
        <span className="dim">
          {plan.estimate.runs === 0
            ? "No finished run of this workflow yet, so there is nothing to estimate from."
            : "You can stop it at any point; stopping never costs more than what has already run."}
        </span>
      </p>
    </section>
  );
}

function Figure({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dd className="mono">{value}</dd>
      <dt>{label}</dt>
    </div>
  );
}

/** The input this workflow expects a file in — the first one typed `path`. */
function fileInputOf(workflow: WorkflowShape): string | null {
  const entry = Object.entries(workflow.inputs).find(([, spec]) => spec.type === "path");
  return entry?.[0] ?? null;
}

/** The plan's guesses as starting values, so the fields are filled but editable. */
function guessed(plan: RunPlan): Record<string, string> {
  return Object.fromEntries(Object.entries(plan.guesses).map(([k, g]) => [k, g.value]));
}

/** Blank fields are left out, so a workflow default is not overwritten with "". */
function filled(values: Record<string, string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values).filter(([, value]) => value != null && String(value).trim() !== ""),
  );
}

function useCatalogue(): Catalogue | null {
  const [catalogue, setCatalogue] = useState<Catalogue | null>(null);
  useEffect(() => {
    let live = true;
    getCatalogue()
      .then((c) => live && setCatalogue(c))
      .catch(() => undefined);
    return () => {
      live = false;
    };
  }, []);
  return catalogue;
}
